library(shiny)
library(DT)
library(tidyverse)
library(jsonlite)
library(shinydashboard)
library(reactable)
library(leaflet)
library(shinycssloaders)
library(shinyWidgets)
library(readr)
library(reactablefmtr)
library(shinyjs)


naics <- read_csv("2017_titles_descriptions.csv")